version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golfclub
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  golfclub-api:
    build: .
    container_name: golfclub-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
